import os
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import Connection, Engine, create_engine, text

from app.config import settings
from app.main import app

ROOT = Path(__file__).parent.parent
EVIDENCE_DIR = Path(__file__).parent / "evidence"

_test_results: dict[str, str] = {}


def _drop_all_tables(engine: Engine) -> None:
    """Drop every base table in the current database (FK checks bypassed)."""
    with engine.begin() as conn:
        db_name = conn.execute(text("SELECT DATABASE()")).scalar()
        if not db_name:
            raise RuntimeError("no database selected on the test connection")
        rows = conn.execute(
            text(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = :db AND table_type = 'BASE TABLE'
                """,
            ),
            {"db": db_name},
        ).all()
        if not rows:
            return
        conn.execute(text("SET FOREIGN_KEY_CHECKS = 0"))
        for (tbl,) in rows:
            conn.execute(text(f"DROP TABLE IF EXISTS `{tbl}`"))
        conn.execute(text("SET FOREIGN_KEY_CHECKS = 1"))


def _reset_database(engine: Engine) -> None:
    """Wipe the schema and re-run migrate.py to rebuild it from scratch."""
    _drop_all_tables(engine)
    env = os.environ.copy()
    env["DATABASE_URL"] = settings.DATABASE_URL
    result = subprocess.run(
        [sys.executable, str(ROOT / "migrate.py")],
        cwd=str(ROOT),
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"migrate.py failed (exit {result.returncode})\n"
            f"stdout: {result.stdout}\nstderr: {result.stderr}",
        )


@pytest.fixture(scope="session")
def engine() -> Engine:
    """Session-wide SQLAlchemy engine pointing at the configured DATABASE_URL."""
    return create_engine(settings.DATABASE_URL)


@pytest.fixture(scope="session", autouse=True)
def setup_database(engine: Engine) -> Iterator[None]:
    """One-time wipe + migrate at session start. DB is left populated for inspection."""
    _reset_database(engine)
    yield


@pytest.fixture
def client() -> TestClient:
    """Plain TestClient — does NOT reset DB state. Use only for genuinely read-only tests
    that are robust to whatever state the previous test left behind. In this suite all
    tests use `isolated_client` instead, for reproducibility."""
    return TestClient(app)


@pytest.fixture
def isolated_client(engine: Engine) -> TestClient:
    """TestClient that wipes + re-migrates the DB before yielding. Slower, but every
    test starts from a known-good fixture state regardless of prior tests."""
    _reset_database(engine)
    return TestClient(app)


@pytest.fixture
def conn(engine: Engine) -> Iterator[Connection]:
    """Per-test connection wrapped in a transaction that rolls back at teardown.
    Useful for service-level tests that don't go through HTTP. Not used in this suite."""
    with engine.connect() as connection:
        trans = connection.begin()
        try:
            yield connection
        finally:
            trans.rollback()


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):  # type: ignore[no-untyped-def]
    outcome = yield
    report = outcome.get_result()
    if report.when == "call":
        _test_results[item.nodeid] = report.outcome


def pytest_sessionfinish(session, exitstatus) -> None:  # type: ignore[no-untyped-def]
    """Generate tests/evidence/test_plan.md with one entry per test + docstring."""
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    out = EVIDENCE_DIR / "test_plan.md"

    lines = [
        "# HW3 Test Plan and Results",
        "",
        f"Generated by `pytest_sessionfinish` at end of session (exit status: {exitstatus}).",
        "",
        "Each entry is the test node id, status, and the test's docstring.",
        "",
    ]

    for item in session.items:
        status = _test_results.get(item.nodeid, "not-run").upper()
        lines.append(f"### {item.nodeid} — **{status}**")
        doc = (item.function.__doc__ or "").strip()
        if doc:
            for line in doc.splitlines():
                lines.append(f"> {line.strip()}")
        else:
            lines.append("> *(no docstring)*")
        lines.append("")

    out.write_text("\n".join(lines))
